version: '3.8'
services:
    jenkins:
        build: .
        ports:
            - 80:8080
            - 50000:50000
        volumes:
            - "${APP_DATA_DIR:?err}:/var/jenkins_home"
            - /var/run/docker.sock:/var/run/docker.sock
